import { brandName, business, citiesLabel } from "@/data/business";

export const HomepageContentSection = () => {
  return (
    <section id="service-information" className="box-border caret-transparent pt-[70px] pb-0 md:pt-[120px] md:pb-0 bg-transparent">
      <div className="box-border caret-transparent max-w-[1200px] mx-auto px-[15px] md:px-[30px]">
        <div className="box-border caret-transparent mb-12 md:mb-16"><h2 className="text-white text-2xl font-bold box-border caret-transparent leading-[30px] mb-6 sm:text-3xl sm:leading-[38px] md:text-4xl md:leading-[43.2px]">Exterior Cleaning & Lawn Maintenance</h2><p className="text-gray-200 text-base sm:text-lg md:text-xl box-border caret-transparent leading-7 mb-8">{brandName()} helps customers across {citiesLabel()} and {business.region} with the exterior jobs that protect properties and improve kerb appeal. From driveway and patio pressure washing to roof moss removal, gutter clearing, soft wash and lawn care, Jake and Martin handle professional exterior maintenance with reliable service and competitive prices. <a href="/contact" className="text-[#16a34a] hover:underline font-medium">Contact us to discuss your project</a>.</p></div>
        <div className="box-border caret-transparent mb-12 md:mb-16"><h2 className="text-white text-2xl font-bold box-border caret-transparent leading-[30px] mb-6 sm:text-3xl sm:leading-[38px] md:text-4xl md:leading-[43.2px]">Driveway, Patio & Decking Cleaning</h2><p className="text-gray-200 text-base sm:text-lg md:text-xl box-border caret-transparent leading-7 mb-6">We deep clean block paving, tarmac, concrete, patios, paths and decking — removing moss, algae, weeds and years of built-up grime. Biocide treatments and re-sanding are available to help restore colour and prevent regrowth. <a href="/contact" className="text-[#16a34a] hover:underline font-medium">Ask for a driveway or patio quote</a>.</p></div>
        <div className="box-border caret-transparent mb-12 md:mb-16"><h2 className="text-white text-2xl font-bold box-border caret-transparent leading-[30px] mb-6 sm:text-3xl sm:leading-[38px] md:text-4xl md:leading-[43.2px]">Roof Cleaning & Gutter Clearing</h2><p className="text-gray-200 text-base sm:text-lg md:text-xl box-border caret-transparent leading-7 mb-6">Moss and algae on roofs and driveways can cause damage over time — holding moisture against tiles, blocking gutters and creating slippery surfaces. {brandName()} provides safe roof scraping, biocide treatment, gutter clearing and fascia cleaning to protect your property. <a href="/contact" className="text-[#16a34a] hover:underline font-medium">Get a free roof cleaning quote</a>.</p></div>
        <div className="box-border caret-transparent mb-12 md:mb-16"><h2 className="text-white text-2xl font-bold box-border caret-transparent leading-[30px] mb-6 sm:text-3xl sm:leading-[38px] md:text-4xl md:leading-[43.2px]">Grass Cutting & Garden Maintenance</h2><p className="text-gray-200 text-base sm:text-lg md:text-xl box-border caret-transparent leading-7 mb-6">{brandName()} also provides grass cutting, lawn care and garden maintenance across {business.region}. Fully insured, reliable and offering free quotes — message us to book your next visit. <a href="/contact" className="text-[#16a34a] hover:underline font-medium">Book lawn care today</a>.</p></div>
      </div>
    </section>
  );
};
